name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run Pytest
        env:
          DEBUG: "True"
          HOST: "0.0.0.0"
          PORT: "8000"
          CELERY_RESULT_EXPIRES: "43200"

          POSTGRES_USER: "ci_user"
          POSTGRES_PASSWORD: "ci_password"
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: "5432"
          POSTGRES_DB: "ci_db"

          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
          REDIS_DB: "0"
        run: poetry run pytest -v
